system:
  env: release # debug | release | test
  addr: 
  db-type: mysql
  use-redis: true
  use-init: true
  use-task: false
  iplimit-count: 0
  iplimit-time: 0
  router-prefix: "api"

mysql:
  prefix:
  singular: false
  path: 127.0.0.1
  port: 3306
  config: charset=utf8mb4&parseTime=True
  db-name: 
  username: 
  password: 
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: error
  log-zap: false
  engine: 

redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""

client:
  url: 

wss:
  sec-wss-token:

general-account:
  op-sepolia:
    private-key: 
    public-key: 
    receive-account: 

coingecko:
  api-key: 

zap:
  level: info
  format: console
  prefix: "[market/server]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
  max-age: 0

file:
  image-url: 
  image-client-path: "images"
  image-server-path: "resource/images"
  file-url: 
  file-client-path: "files"
  file-server-path: "resource/files"

smtp:
  host: 
  port: 
  username: 
  password: 

blockchain:
  open-sweep-block: false
  sweep-mainnet: false
  ethereum: false
  bitcoin: false
  tron: false
  bsc: false
  litecoin: false
  op: true
  arbitrum-one: false
  arbitrum-nova: false

blockchain-plugin:
  bitcoin: 
  litecoin: 

telegram:
  inform-bot-link:
  inform-bot-token:
  inform-channel-id:
  notification-bot-link:
  notification-bot-token:
  notification-bot-id:
